//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dota
{
    using System;
    using System.Collections.Generic;
    
    public partial class games
    {
        public int id { get; set; }
        public Nullable<int> dire_team_id { get; set; }
        public Nullable<int> radiant_team_id { get; set; }
        public Nullable<int> dire_kills { get; set; }
        public Nullable<int> radiant_kills { get; set; }
        public Nullable<System.DateTime> game_start { get; set; }
        public Nullable<System.DateTime> game_end { get; set; }
        public Nullable<int> tournament_id { get; set; }
        public Nullable<sbyte> is_played { get; set; }
    
        public virtual teams teams { get; set; }
        public virtual teams teams1 { get; set; }
        public virtual tournaments tournaments { get; set; }
    }
}
