//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dota
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dota2Entities : DbContext
    {
        public dota2Entities()
            : base("name=dota2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<games> games { get; set; }
        public virtual DbSet<players> players { get; set; }
        public virtual DbSet<players_positions> players_positions { get; set; }
        public virtual DbSet<regions> regions { get; set; }
        public virtual DbSet<teams> teams { get; set; }
        public virtual DbSet<tournaments> tournaments { get; set; }
    }
}
