//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dota
{
    using System;
    using System.Collections.Generic;
    
    public partial class players
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string nickname { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public string profile_photo { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual teams teams { get; set; }
        public virtual players_positions players_positions { get; set; }
    }
}
